apiVersion: batch/v1
kind: CronJob
metadata:
  name: pubg-scraper
spec:
  schedule: "0 0 * * *"
  timeZone: "Etc/UTC"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: pubg
          containers:
            - name: pubg-scrape
              image: "pubg-scraper:latest"
              imagePullPolicy: Never
              args:
                - "python"
                - "pubg/job.py"
              envFrom:
                - configMapRef:
                    name: redis-config
              volumeMounts:
                - name: secret-volume
                  mountPath: /etc/secrets/
                  readOnly: true
              resources:
                requests:
                  cpu: 500m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
          restartPolicy: OnFailure
          volumes:
            - name: secret-volume
              secret:
                secretName: pubg-scraper-secret